### ISSUE TITLE
Cannot specify gemfile name

### ISSUE THREAD

**Issue by jeremyevans** [ioquatix/bake-test-external#5]
Currently, this only looks for `Gemfile` and `gems.rb` in the repository directory.  This prevents me from adding Roda as a external test for Rack, since Roda uses `.ci.gemfile`.  Can we support an optional `:gemfile` entry (similar to `:url` and `:command`), and have it respected and set `BUNDLE_GEMFILE` in the environment when running `bundle install`?

FWIW, instead of modifying the gemfile, you could probably set `RUBYLIB` in the environment to include a path to the lib directory of the repository being tested.  I think that should take precedence over the load paths added by `bundle exec`, but I haven't tested that approach.

**Comment by ioquatix** [comment]
I'm okay to make those improvements. Maybe we can specify a `gemfile:` configuration?

I'm okay with not rewriting the gemfile, but I've had a lot of trouble getting things to work. I believe bundler should provide a proper override mechanism. If you have better ideas, I'm happy to receive them.

**Comment by jeremyevans** [comment]
`gemfile:` configuration should be sufficient.  If there were problems with not modifying the gemfile, then no need to spend more time on that approach.

**Comment by ioquatix** [comment]
Added `gemfile:` configuration: <https://ioquatix.github.io/bake-test-external/guides/getting-started/index#custom-gemfile>

Released in v0.4.0 - please try it out and let me know if it's working as expected.
